export const contactEmail = "sarathss.g727@gmail.com";

export const toolLogos = [
  { name: "Python", path: "/assets/logos/python.svg" },
  { name: "SQL", path: "/assets/logos/postgresql.svg" },
  { name: "AWS", path: "/assets/logos/aws.svg" },
  { name: "Amazon S3", path: "/assets/logos/amazon-s3.svg" },
  { name: "Snowflake", path: "/assets/logos/snowflake.svg" },
  { name: "BigQuery", path: "/assets/logos/google-bigquery.svg" },
  { name: "Apache Spark", path: "/assets/logos/apache-spark.svg" },
  { name: "Apache Kafka", path: "/assets/logos/apache-kafka.svg" },
  { name: "Apache Airflow", path: "/assets/logos/apache-airflow.svg" },
  { name: "Databricks", path: "/assets/logos/databricks.svg" },
  { name: "Power BI", path: "/assets/logos/power-bi.svg" },
  { name: "Tableau", path: "/assets/logos/tableau.svg" },
  { name: "Looker", path: "/assets/logos/looker.svg" },
  { name: "Docker", path: "/assets/logos/docker.svg" },
  { name: "Kubernetes", path: "/assets/logos/kubernetes.svg" },
  { name: "GitHub Actions", path: "/assets/logos/github-actions.svg" },
];

export const skillGroups = [
  {
    title: "Programming & Querying",
    items: [
      "Python",
      "SQL",
      "PySpark",
      "Scala",
      "Java",
      "R",
      "Pandas",
      "NumPy",
      "CTEs",
      "Window Functions",
      "SQL Performance Tuning",
      "Exploratory Data Analysis",
      "Root-Cause Analysis",
      "Trend Analysis",
      "Segmentation Analysis",
      "Ad-Hoc Analysis",
    ],
  },
  {
    title: "Cloud & Data Platforms",
    items: [
      "AWS",
      "Amazon S3",
      "AWS Glue",
      "Amazon Redshift",
      "AWS Lambda",
      "Amazon EMR",
      "Athena",
      "IAM",
      "KMS",
      "Snowflake",
      "BigQuery",
      "PostgreSQL",
      "SQL Server",
      "MySQL",
      "DynamoDB",
      "Alation",
    ],
  },
  {
    title: "ETL, Orchestration & Streaming",
    items: [
      "Apache Airflow",
      "dbt",
      "AWS Glue Jobs",
      "Lambda-Based Pipelines",
      "Batch Processing",
      "Streaming Pipelines",
      "Automated Workflow Scheduling",
      "Apache Spark",
      "Spark Streaming",
      "Apache Kafka",
      "Kafka Streams",
      "Apache Flink",
      "Hadoop",
      "Hive",
      "Micro-Batch Processing",
    ],
  },
  {
    title: "Warehousing, Modeling & Quality",
    items: [
      "Dimensional Modeling",
      "Star Schema",
      "Fact & Dimension Tables",
      "Data Marts",
      "Data Lakes",
      "Lakehouse Architecture",
      "Delta Lake",
      "Schema Evolution",
      "Parquet",
      "JSON",
      "Data Validation",
      "Metric Reconciliation",
      "Great Expectations",
      "Data Contracts",
      "SLA Monitoring",
      "Automated Quality Checks",
      "Data Lineage",
      "Metadata Documentation",
    ],
  },
  {
    title: "Analytics, BI & Governance",
    items: [
      "Power BI",
      "Tableau",
      "Looker",
      "Amazon QuickSight",
      "Excel PivotTables",
      "Advanced Excel Formulas",
      "Power Query",
      "Executive Dashboards",
      "KPI Reporting",
      "Self-Service Analytics",
      "Forecasting",
      "Statistical Analysis",
      "A/B Testing",
      "Data Storytelling",
      "Data Dictionaries",
      "Business Glossary",
      "Metric Definitions",
      "Audit-Ready Documentation",
      "CCPA",
      "GDPR",
      "VPPA",
    ],
  },
  {
    title: "DevOps, APIs & Delivery",
    items: [
      "Docker",
      "Kubernetes Basics",
      "Git",
      "GitHub Actions",
      "CI/CD Pipelines",
      "Linux CLI",
      "RESTful APIs",
      "FastAPI",
      "Playwright",
      "Technical Documentation",
      "Secure Data Handling",
    ],
  },
];

export const roleCards = [
  {
    title: "Data Analyst",
    level: "Business intelligence, KPI trust, and decision-ready analytics",
    href: "#/data-analyst",
    desc: "Dashboards, customer analytics, metric governance, reporting layers, experimentation, and stakeholder-facing insight delivery.",
    tags: ["SQL", "Power BI", "Tableau", "Snowflake", "BigQuery", "Data Quality"],
  },
  {
    title: "Data Engineer",
    level: "Advanced pipelines, lakehouse architecture, and governed data products",
    href: "#/data-engineer",
    desc: "Cloud ETL/ELT, Spark, Kafka, Airflow, dbt, warehouse models, data observability, and analytics-ready infrastructure.",
    tags: ["Python", "AWS", "Spark", "Kafka", "Airflow", "dbt"],
  },
];

export const myProjects = [
  {
    id: 1,
    title: "Amazon Kindle ETL & Analytics Pipeline",
    desc:
      "Cloud-native ETL pipeline that ingests, cleans, transforms, and loads Kindle sales and review datasets into an analytics-ready Redshift warehouse.",
    subdesc: [
      "Built reusable Python and SQL transformations with schema standardization for BI reporting, forecasting, and machine-learning-ready analytics.",
      "Used AWS S3, Glue, Redshift, and data quality checks to improve reliability across raw, curated, and reporting layers.",
      "Designed the warehouse output around consistent business metrics, reusable analytical datasets, and repeatable refresh patterns.",
    ],
    href: "",
    spotlight: "/assets/projects/accessories.jpg",
    tags: [
      { id: 1, name: "AWS", path: "/assets/logos/aws.svg" },
      { id: 2, name: "Redshift", path: "/assets/logos/aws.svg" },
      { id: 3, name: "S3", path: "/assets/logos/amazon-s3.svg" },
      { id: 4, name: "Python", path: "/assets/logos/python.svg" },
      { id: 5, name: "SQL", path: "/assets/logos/postgresql.svg" },
    ],
  },
  {
    id: 2,
    title: "Enterprise Data Lakehouse Modernization",
    desc:
      "Scalable AWS lakehouse pattern that turns raw operational data into curated analytical layers with reliability checks and schema control.",
    subdesc: [
      "Designed S3, Glue, EMR Spark, and Delta Lake layers for partitioned data storage, schema enforcement, and reproducible processing.",
      "Added Great Expectations-style validation, data quality gates, and documentation to reduce recurring pipeline failures.",
      "Optimized Spark jobs through partitioning, query tuning, and structured exception handling.",
    ],
    href: "",
    spotlight: "/assets/projects/blazor-app.jpg",
    tags: [
      { id: 1, name: "Spark", path: "/assets/logos/apache-spark.svg" },
      { id: 2, name: "Delta Lake", path: "/assets/logos/databricks.svg" },
      { id: 3, name: "Glue", path: "/assets/logos/aws.svg" },
      { id: 4, name: "EMR", path: "/assets/logos/aws.svg" },
    ],
  },
  {
    id: 3,
    title: "Real-Time Streaming & Data Observability Platform",
    desc:
      "Near real-time ingestion and observability platform for monitoring freshness, schema drift, SLA adherence, and anomaly patterns.",
    subdesc: [
      "Created event-driven ingestion with Kafka and Apache Flink, then orchestrated downstream checks through Airflow workflows.",
      "Tracked data freshness, schema drift, exceptions, and operational SLA signals across streaming datasets.",
      "Structured alerting and documentation so data teams could triage issues before they reached reporting users.",
    ],
    href: "",
    spotlight: "/assets/projects/game-engine.jpg",
    tags: [
      { id: 1, name: "Kafka", path: "/assets/logos/apache-kafka.svg" },
      { id: 2, name: "Flink", path: "/assets/logos/apache-flink.svg" },
      { id: 3, name: "Airflow", path: "/assets/logos/apache-airflow.svg" },
      { id: 4, name: "DataHub", path: "/assets/logos/cdc.svg" },
    ],
  },
  {
    id: 4,
    title: "Enterprise Customer Data Quality & KPI Governance",
    desc:
      "Customer analytics and KPI governance framework that improves metric trust, dashboard consistency, and audit-ready reporting.",
    subdesc: [
      "Built SQL and Python validation checks to reconcile KPI logic across source systems, dashboards, and trusted datasets.",
      "Developed Power BI and Tableau reporting outputs with documented metric definitions, assumptions, and quality rules.",
      "Reduced reporting discrepancies by strengthening data dictionaries, business glossaries, and data quality monitoring.",
    ],
    href: "",
    spotlight: "/assets/projects/auth-system.jpg",
    tags: [
      { id: 1, name: "Snowflake", path: "/assets/logos/snowflake.svg" },
      { id: 2, name: "Power BI", path: "/assets/logos/power-bi.svg" },
      { id: 3, name: "Tableau", path: "/assets/logos/tableau.svg" },
      { id: 4, name: "Python", path: "/assets/logos/python.svg" },
    ],
  },
  {
    id: 5,
    title: "Inventory Forecasting & Optimization Pipeline",
    desc:
      "Automated forecasting pipeline that turns item-level sales and inventory data into forecasts, safety stock outputs, and reorder recommendations.",
    subdesc: [
      "Applied ETL, feature engineering, statistical forecasting, and machine-learning-ready transformations.",
      "Used Python, SQL, Spark, and dashboard-ready outputs to support inventory decision-making and demand planning.",
      "Created reusable reporting logic for procurement and operations teams.",
    ],
    href: "",
    spotlight: "/assets/projects/elearning.jpg",
    tags: [
      { id: 1, name: "Python", path: "/assets/logos/python.svg" },
      { id: 2, name: "SQL", path: "/assets/logos/postgresql.svg" },
      { id: 3, name: "Spark", path: "/assets/logos/apache-spark.svg" },
      { id: 4, name: "Forecasting", path: "/assets/logos/scikit-learn.svg" },
    ],
  },
  {
    id: 6,
    title: "Fraud Analytics & Payment Risk Scoring Insights",
    desc:
      "Risk analytics pipeline and dashboard layer for monitoring payment-risk patterns, anomaly indicators, and emerging risk trends.",
    subdesc: [
      "Developed structured datasets and Power BI views to support fraud investigation, risk monitoring, strategy tracking, and mitigation analysis.",
      "Implemented reconciliation, drift, and quality checks to improve reliability of risk analytics outputs.",
      "Improved analytical responsiveness by organizing fraud signals into trusted, reusable reporting layers.",
    ],
    href: "",
    spotlight: "/assets/projects/wordpress-theme.jpg",
    tags: [
      { id: 1, name: "Power BI", path: "/assets/logos/power-bi.svg" },
      { id: 2, name: "Excel", path: "/assets/logos/vba.svg" },
      { id: 3, name: "SQL", path: "/assets/logos/postgresql.svg" },
      { id: 4, name: "Python", path: "/assets/logos/python.svg" },
    ],
  },
];

export const experiences = [
  {
    title: "Data Analyst",
    job: "General Data",
    date: "Feb 2026 - Present",
    contents: [
      "Design interactive Tableau and Power BI dashboards that translate complex analytical outputs into actionable executive insights.",
      "Build scalable ETL pipelines with Python, SQL, AWS, and Snowflake while maintaining data quality, consistency, and reliability.",
      "Perform descriptive, diagnostic, predictive, A/B testing, and ad-hoc analysis for Marketing, Sales, Product, and leadership stakeholders.",
      "Document pipelines, models, KPI logic, analytical methodology, and governance practices for reproducible analytics delivery.",
    ],
  },
  {
    title: "Data Engineer / Senior Data Analyst",
    job: "University of Cincinnati",
    date: "Jun 2025 - Aug 2025",
    contents: [
      "Architected Python, SQL, AWS S3, Spark, Delta Lake, and API-driven pipelines for SEC EDGAR and NHTSA data ingestion.",
      "Built automated reporting pipelines processing 100K+ monthly records and supported dashboards for leadership KPI monitoring.",
      "Implemented validation, metric reconciliation, freshness checks, and consistency controls that reduced reporting discrepancies by 35%.",
      "Containerized a FastAPI and Docker data-processing service with structured logging, checkpointing, and exception handling.",
    ],
  },
  {
    title: "Data Engineer / Analytics Lead",
    job: "University of Cincinnati NEO Initiative",
    date: "Sep 2024 - Mar 2025",
    contents: [
      "Designed dbt transformation models, BigQuery data marts, semantic layers, and warehouse-optimized KPI datasets.",
      "Orchestrated Airflow ETL/ELT workflows with task dependencies, incremental loads, retries, failure handling, and SLA monitoring.",
      "Created data dictionaries, KPI definitions, business logic documentation, quality rules, and reporting methodology notes.",
      "Improved dashboard responsiveness by 50% through high-performance BigQuery marts and reusable reporting layers.",
    ],
  },
  {
    title: "Quality Specialist - Data Engineer",
    job: "Amazon",
    date: "Nov 2021 - Aug 2023",
    contents: [
      "Built PySpark, SQL, AWS S3, EMR, Glue, Redshift, Snowflake, Hive, and Kafka workflows for logistics and operational quality datasets.",
      "Analyzed 5TB+ monthly supply-chain data, optimized SQL and Spark transformations, and accelerated reporting refresh cycles by 45%.",
      "Implemented validation frameworks, anomaly detection, CloudWatch monitoring, schema drift checks, and near real-time data freshness monitoring.",
      "Partnered with operations, quality, and engineering teams to solve recurring delivery defects and strengthen SLA adherence.",
    ],
  },
  {
    title: "Data Analyst / Jr. Construction Manager",
    job: "Hasini Infra Constructions & Developers",
    date: "Mar 2019 - Oct 2021",
    contents: [
      "Automated financial ETL routines with SQL, Power Query, Excel macros, and Python scripts, reducing manual work by 30+ hours per month.",
      "Centralized operational data from 5+ construction sites into a SQL database for visibility into a $2.5M+ project portfolio.",
      "Designed Power BI dashboards and forecasting views that surfaced cost risks earlier and helped prevent six-figure potential overruns.",
      "Created validation templates and reporting standards that improved data accuracy by 15% and accelerated monthly reconciliation.",
    ],
  },
];

export const certifications = [
  "Palantir Foundry & AIP Builder Foundations",
  "AWS Certified Cloud Practitioner",
  "Databricks Fundamentals",
  "Google AI Essentials",
  "Google Data Analytics Professional Certificate",
  "Tata Data Visualization",
  "Tableau",
  "SQL Essential Training",
];

export const education = [
  "University of Cincinnati | Master of Science, Business Analytics | GPA: 3.85 | Dec 2025",
  "Bapatla Engineering College | B.Tech, Civil Engineering | GPA: 3.2 | Apr 2018",
];
